__target__: definitions.BirdClassifierArguments
training:
  __target__: definitions.TrainingArguments
  lightning_checkpoint:
    dirpath: "./experiments/original_code_adamw"
    filename: Net-{epoch:02d}
    save_last: true
    save_on_train_epoch_end: true
    every_n_epochs: 2
    verbose: true
    monitor: validation/accuracy/classification
    mode: max
  run_name: original_code_adamw
  seed: 42
  batch_size: 64
  num_workers: 8
  learning_rate: 1e-3
  epochs: 10
  adam_eps: 1e-6
  adam_weight_decay: 0.1
  adam_betas:
  - 0.9
  - 0.98

datasets:
  __target__: definitions.DatasetArguments
  train_dir: bird_dataset/train_images/
  val_dir: bird_dataset/val_images/
  num_classes: 20
