__target__: definitions.BirdClassifierArguments
training:
  __target__: definitions.TrainingArguments
  lightning_checkpoint:
    dirpath: "./experiments/original_code"
    filename: Net-{epoch:02d}
    save_last: true
    save_on_train_epoch_end: true
    verbose: true
    monitor: validation/accuracy/classification
    mode: max
  run_name: original_code
  seed: 42
  batch_size: 64
  num_workers: 8
  learning_rate: 1e-1
  epochs: 10
  momentum: 0.5

datasets:
  __target__: definitions.DatasetArguments
  train_dir: bird_dataset/train_images/
  val_dir: bird_dataset/val_images/
  num_classes: 20
